name = "CNThermSci"
uuid = "b09fce01-7ee8-4c29-994d-861f9da62320"
repo = "https://github.com/CNThermSci/CNThermSci.git"
description = "CNThermSci registry"

[packages]
e1e7c491-b663-4f99-9eec-1cfab755363a = { name = "SliderCrankGeometry", path = "S/SliderCrankGeometry" }
